service: laconia-acceptance

provider:
  name: aws
  runtime: nodejs6.10
  stage: test
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "lambda:InvokeAsync"
      Resource: "*"
  environment:
    TRACKER_BUCKET_NAME: ${self:custom.trackerBucketName}
    TEST_BUCKET_NAME: ${self:custom.testBucketName}

custom:
  fullName: ${self:service}-${self:provider.stage}
  trackerBucketName: ${self:custom.fullName}-tracker
  testBucketName: ${self:custom.fullName}-bucket
  
functions:
  handler-basic:
    handler: src/handler/basic.handler
  handler-recursive:
    handler: src/handler/recursive.handler
  batch-s3:
    handler: src/batch/s3.handler
    timeout: 6

resources:
  Resources:
    S3Tracker:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.trackerBucketName}
    TestBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.testBucketName}
