service: laconia-acceptance

plugins:
  - serverless-s3-remover
  - serverless-s3-sync
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: ${env:NODE_RUNTIME, 'nodejs8.10' }
  stage: ${env:NODE_VERSION, 'node8' }
  region: ${env:AWS_REGION, 'eu-west-1'}
  tracing: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "lambda:InvokeAsync"
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
      Resource: "arn:aws:ssm:*:*:parameter/${self:custom.fullName}/*"
  environment:
    TRACKER_BUCKET_NAME: ${self:custom.trackerBucketName}
    LACONIA_TEST_SPY_BUCKET: ${self:custom.trackerBucketName}

custom:
  fullName: ${self:service}-${self:provider.stage}
  trackerBucketName: ${self:custom.fullName}-tracker
  totalOrderBucketName: ${self:custom.fullName}-total-order
  restaurantBucketName: ${self:custom.fullName}-restaurant
  orderDynamoDbBatchTableName: ${self:custom.fullName}-order
  remover:
    buckets:
      - ${self:custom.trackerBucketName}
  s3Sync:
    - bucketName: ${self:custom.restaurantBucketName}
      localDir: src/resources

functions:
  place-order:
    handler: src/place-order.handler
    events:
      - http:
          path: order
          method: post
    environment:
      ORDER_TABLE_NAME: ${self:custom.orderDynamoDbBatchTableName}
      LACONIA_CONFIG_API_KEY: ssm:/${self:custom.fullName}/apikey
      LACONIA_CONFIG_RESTAURANTS: s3:${self:custom.restaurantBucketName}/restaurants.json
      LACONIA_CONFIG_ENABLED: boolean:true
  process-card-payments:
    timeout: 6 # Force recursion
    handler: src/process-card-payments.handler
    environment:
      LACONIA_INVOKER_CAPTURE_CARD_PAYMENT: ${self:custom.fullName}-capture-card-payment
      ORDER_TABLE_NAME: ${self:custom.orderDynamoDbBatchTableName}
  capture-card-payment:
    handler: src/capture-card-payment.handler
  calculate-total-order:
    timeout: 6 # Force recursion
    handler: src/calculate-total-order.handler
    environment:
      RESTAURANT_BUCKET_NAME: ${self:custom.restaurantBucketName}
      TOTAL_ORDER_BUCKET_NAME: ${self:custom.totalOrderBucketName}
      ORDER_TABLE_NAME: ${self:custom.orderDynamoDbBatchTableName}

resources:
  Resources:
    S3Tracker:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.trackerBucketName}
    TotalOrderBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.totalOrderBucketName}
    RestaurantBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.restaurantBucketName}
    OrderTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "orderId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "orderId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.orderDynamoDbBatchTableName}
