defaults: &defaults
  docker:
    - image: circleci/node:8.10.0-browsers
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run publish:coverage
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/*/node_modules

  integration_test:
    <<: *defaults
    
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install
      - run: npm run test:integration

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - integration_test:
          requires:
            - build
