version: 2.1

commands:
  build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
            - v1-{{ .Environment.CIRCLE_JOB }}-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run: npm run test:circleci
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/*/node_modules
  integration_test:
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
            - v1-{{ .Environment.CIRCLE_JOB }}-
      - run: npm run test:integration
      - save_cache:
          paths:
            - /tmp/dynamodb-local
          key: v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}

jobs:
  build_node8:
    docker:
      - image: circleci/node:8.10.0-browsers
    working_directory: ~/repo
    steps:
      - build
  build_node10:
    docker:
      - image: circleci/node:10.16-browsers
    working_directory: ~/repo
    steps:
      - build
      - run: 'if [ -n "$COVERALLS_REPO_TOKEN" ]; then npm run publish:coverage;
          fi' # COVERALLS_REPO_TOKEN does not run on fork

  license_test:
    docker:
      - image: circleci/node:10.16-browsers
    working_directory: ~/repo
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: fossa init
      - run: fossa analyze

  integration_test_node8:
    docker:
      - image: circleci/node:8.10.0-browsers
    working_directory: ~/repo
    steps:
      - integration_test

  integration_test_node10:
    docker:
      - image: circleci/node:10.16-browsers
    working_directory: ~/repo
    steps:
      - integration_test

workflows:
  pipeline:
    jobs:
      - build_node8
      - build_node10
      - license_test:
          filters:
            branches:
              only: master
      - integration_test_node8:
          requires:
            - build_node8
      - integration_test_node10:
          requires:
            - build_node10
